analytics: {}
color:
  brandColors:
    - '#535357'
    - '#ffffff'
    - '#e3b82d'
    - '#8e9892'
    - '#1e1b23'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.535362
name: The Grid Support
opengraph: {}
purpose: []
typography_spectrum: 0.24741
navigation:
  - url: 'https://thegrid.io/'
    name: Home
  - url: 'https://blog.thegrid.io/'
    name: Blog
  - url: 'http://status.thegrid.io/'
    name: Status
