name: TheGridSupport
favicon: null
layout_spectrum: 0.2798
typography_spectrum: 0.3658
title: The Grid Support Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030405'
    - '#f6d15b'
    - '#b99d45'
    - '#6f5f2b'
    - '#faf9fb'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
