name: TheGridSupport
favicon: null
layout_spectrum: 0.50241
typography_spectrum: 0.20515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1a21'
    - '#ffec12'
    - '#8bb9bb'
    - '#beffff'
    - '#627f83'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
