analytics: {}
color:
  brandColors:
    - '#030405'
    - '#f6d15b'
    - '#b99d45'
    - '#6f5f2b'
    - '#faf9fb'
  brandStrength: 0.662007
  lightness: 0.494243
  rhythmicContrast: 0.604441
  saturation: 0.675987
cta: {}
layout_spectrum: 0.5129
name: TheGridSupport
opengraph: {}
purpose: []
typography_spectrum: 0.069901
