name: TheGridSupport
favicon: null
layout_spectrum: 0.26105
typography_spectrum: 0.16627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030405'
    - '#f6d15b'
    - '#b99d45'
    - '#6f5f2b'
    - '#faf9fb'
  brandStrength: 0.662007
  lightness: 0.494243
  saturation: 0.675987
  rhythmicContrast: 0.604441
purpose: []
