typography_spectrum: 0.24741
color:
  brandColors:
    - '#535357'
    - '#ffffff'
    - '#e3b82d'
    - '#8e9892'
    - '#1e1b23'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 0
opengraph: {}
layout_spectrum: 0.535362
analytics: {}
name: Support
cta: {}
navigation:
  - name: Home
    url: 'https://thegrid.io/'
    type: external
  - name: Blog
    url: 'https://blog.thegrid.io/'
    type: external
  - name: Status
    url: 'http://status.thegrid.io/'
    type: external
  - name: The Grid Help Articles
    url: 'http://help.thegrid.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/922062ad-706e-46f7-972a-3c3746548872.png
purpose: []
