name: The Grid Support
favicon: null
layout_spectrum: 0.50241
typography_spectrum: 0.24065
title: The Grid Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#535357'
    - '#ffffff'
    - '#e3b82d'
    - '#8e9892'
    - '#1e1b23'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
