typography_spectrum: 0.24741
color:
  brandColors:
    - '#535357'
    - '#ffffff'
    - '#e3b82d'
    - '#8e9892'
    - '#1e1b23'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 0
opengraph: {}
layout_spectrum: 0.535362
analytics: {}
name: The Grid Support
cta: {}
navigation:
  - url: 'https://thegrid.io/'
    name: Home
  - url: 'https://blog.thegrid.io/'
    name: Blog
  - url: 'http://status.thegrid.io/'
    name: Status
  - id: 'http://help.thegrid.io/'
    url: 'http://help.thegrid.io/'
    name: The Grid Help Articles
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/922062ad-706e-46f7-972a-3c3746548872.png
purpose: []
