name: TheGridSupport
favicon: null
layout_spectrum: 0.48605
typography_spectrum: 0.50781
title: The Grid Support Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030405'
    - '#f6d15b'
    - '#b99d45'
    - '#6f5f2b'
    - '#faf9fb'
  brandStrength: 0.40214198478497565
  lightness: 0.047098432667553425
  saturation: 0.375
  rhythmicContrast: 0.7259041036013514
purpose: []
