name: TheGridSupport
favicon: null
layout_spectrum: 0.2728
typography_spectrum: 0.48205
title: The Grid Support Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030405'
    - '#f6d15b'
    - '#b99d45'
    - '#6f5f2b'
    - '#faf9fb'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
