analytics: {}
color:
  brandColors:
    - '#535357'
    - '#ffffff'
    - '#e3b82d'
    - '#8e9892'
    - '#1e1b23'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.50241
name: TheGridSupport
opengraph: {}
purpose: []
typography_spectrum: 0.24065
